# SPDX-License-Identifier: Apache-2.0
---
# Variables specific to Microsoft Azure platform, Virtual Machines for IBM Db2 HADR

# Platform identifier
__sap_ha_install_anydb_ibmdb2_platform: cloud_msazure_vm

# Azure-specific fence agent packages
__sap_ha_install_anydb_ibmdb2_fence_agent_packages_platform:
  - fence-agents-azure-arm

# Azure-specific VIP management method
__sap_ha_install_anydb_ibmdb2_vip_method: azure_lb

# Azure-specific health check configuration
__sap_ha_install_anydb_ibmdb2_healthcheck_enabled: true

# Made with Bob
