# SPDX-License-Identifier: Apache-2.0
---

# IBM Db2 with an Integrated Cluster Manager permits various options, such as the option to use 'Integrated Linux Pacemaker'.
# See IBM Db2 Supported cluster management software - https://www.ibm.com/docs/en/db2/11.5?topic=clustering-supported-cluster-management-software

# IBM Db2 with 'Integrated Linux Pacemaker' can use two deployment models, either:
# - High Availability and Disaster Recovery (HADR) option for Idle Standby. Used by this Ansible Role.
# - Mutual Failover option

# Execute IBM Db2 with 'Integrated Linux Pacemaker' using Resource Agents db2ethmon, db2inst (HADR), db2hadr (HADR), db2partition and db2fs
# HA Deployment Model: High Availability and Disaster Recovery (HADR) for Idle Standby
# Configurations performed for: root OS user, IBM Db2 Database Administrator OS user (e.g. db2<db2_sid>)
# Configurations executed on: IBM Db2 Primary Node, IBM Db2 Secondary Node

# See SAP Note 1555903 - DB6: Supported IBM Db2 Database Features
# See SAP Note 3100330 - DB6: Using Db2 HADR with Pacemaker Cluster Software
# See SAP Note 3100287 - DB6: Db2 Support for Pacemaker Cluster Software
# See IBM Db2 for SAP HADR reference document referred from sap.com - https://ibm.github.io/db2-hadr-wiki/
# See Admin documentation for IBM Db2 with Integrated Cluster Manager (Linux Pacemaker) - https://www.ibm.com/docs/en/db2/11.5?topic=feature-integrated-solution-using-pacemaker
# See Installation documentation for IBM Db2 with Integrated Cluster Manager (Linux Pacemaker) - https://www.ibm.com/docs/en/db2/11.5?topic=manager-installing-pacemaker-cluster

### Gather required facts
- name: SAP HA AnyDB - IBM Db2 HADR - Collect required facts
  ansible.builtin.setup:
    gather_subset: hardware,interfaces
  tags: always

### Detection and Validation of included variables
# Validation of user vars and included vars for detected platform and OS.
- name: "SAP HA AnyDB IBM Db2 - Include detection and variable inclusion tasks"
  ansible.builtin.import_tasks:
    file: include_vars/include_main.yml
  tags: always

### Pre-checks and validations
- name: SAP HA AnyDB - IBM Db2 HADR - Confirm IBM Db2 installation media is available
  ansible.builtin.find:
    paths: "{{ sap_ha_install_anydb_ibmdb2_software_directory }}"
    recurse: true
    file_type: file
    patterns: db2installPCMK
    excludes: bin
  register: __sap_ha_install_anydb_ibmdb2_check_install_media

- name: SAP HA AnyDB - IBM Db2 HADR - Fail if IBM Db2 installation media is not available
  ansible.builtin.fail:
    msg: IBM Db2 installation media is not available, cannot find file db2installPCMK
  when: not (__sap_ha_install_anydb_ibmdb2_check_install_media.files | length > 0)

# Use the IBM Db2 Performance Diagnostics tool
# Reasons for noqa:
# - no-changed-when: Db2 PD tool is to retrieve information and perform no change
# - risky-shell-pipe: csh cannot use 'set -o pipefail &&' and will error with 'set: Variable name must begin with a letter'
- name: SAP HA AnyDB - IBM Db2 HADR - Confirm if IBM HADR is already activated (i.e. re-run) # noqa no-changed-when risky-shell-pipe
  ansible.builtin.shell: |
    set ibmdb2_sid="{{ sap_ha_install_anydb_ibmdb2_sid }}"
    db2pd -hadr -db $ibmdb2_sid | grep 'HADR_CONNECT_STATUS =' | tr -d ' ' || echo ''
  register: __sap_ha_install_anydb_ibmdb2_hadr_initial_status
  become: true
  become_user: db2{{ sap_ha_install_anydb_ibmdb2_sid | lower }}
  args:
    executable: /bin/csh

- name: SAP HA AnyDB - IBM Db2 HADR - Warning if IBM Db2 HADR is already activated
  ansible.builtin.debug:
    msg: WARNING - IBM Db2 HADR is already activated, some steps will be skipped and some may fail
  when: __sap_ha_install_anydb_ibmdb2_hadr_initial_status.stdout == "HADR_CONNECT_STATUS=CONNECTED"

### Pre-Tasks before configuring IBM Db2 HADR
# Following tasks will execute actual changes on the target systems
- name: "SAP HA AnyDB IBM Db2 - Include pre-tasks"
  ansible.builtin.include_tasks:
    file: pre_tasks/pre_main.yml
    apply:
      tags: pre_db2_hadr
  tags: pre_db2_hadr

### Post-Tasks for verification
- name: "SAP HA AnyDB IBM Db2 - Include post-tasks"
  ansible.builtin.include_tasks:
    file: post_tasks/post_main.yml
    apply:
      tags: post_db2_hadr
  tags: post_db2_hadr


