# SPDX-License-Identifier: Apache-2.0
---
# Post-tasks for IBM Db2 HADR verification

# Use the Pacemaker Shell 'crmsh'
# Reasons for noqa:
# - no-changed-when: Use crmsh to retrieve information and perform no change
- name: SAP HA AnyDB - IBM Db2 HADR - Verify crm for IBM Db2 HA Linux Pacemaker initialisation # noqa no-changed-when
  ansible.builtin.shell: |
    crm --display=plain configure show
    echo -e "\n\n"
    crm --display=plain status full
  register: __sap_ha_install_anydb_ibmdb2_pcmk_check
  when:
    - sap_ha_install_anydb_ibmdb2_hostname_primary == inventory_hostname_short

# db2cm script must run as root
# Reasons for noqa:
# - no-changed-when: Use db2cm script to retrieve information and perform no change
- name: SAP HA AnyDB - IBM Db2 HADR - Verify db2cm for IBM Db2 HA Linux Pacemaker initialisation # noqa no-changed-when
  ansible.builtin.shell: |
    export ibmdb2_instance="db2{{ sap_ha_install_anydb_ibmdb2_sid | lower }}"
    /db2/$ibmdb2_instance/sqllib/bin/db2cm -list
  register: __sap_ha_install_anydb_ibmdb2_init_check
  when:
    - sap_ha_install_anydb_ibmdb2_hostname_primary == inventory_hostname_short

# Use the IBM Db2 Command Line Processor
# Reasons for noqa:
# - no-changed-when: Use Db2 CLP to retrieve information and perform no change
# - risky-shell-pipe: csh cannot use 'set -o pipefail &&' and will error with 'set: Variable name must begin with a letter'
- name: SAP HA AnyDB - IBM Db2 HADR - Verify IBM Db2 HADR configuration # noqa no-changed-when risky-shell-pipe
  ansible.builtin.shell: |
    set ibmdb2_sid="{{ sap_ha_install_anydb_ibmdb2_sid }}"
    db2 get db cfg for $ibmdb2_sid | grep 'Rollforward\|HADR'
  register: __sap_ha_install_anydb_ibmdb2_hadr_config
  become: true
  become_user: db2{{ sap_ha_install_anydb_ibmdb2_sid | lower }}
  args:
    executable: /bin/csh
  when:
    - sap_ha_install_anydb_ibmdb2_hostname_primary == inventory_hostname_short

# Use the IBM Db2 Command Line Processor
# Reasons for noqa:
# - no-changed-when: Use Db2 CLP to retrieve information and perform no change
- name: SAP HA AnyDB - IBM Db2 HADR - Verify IBM Db2 HADR status # noqa no-changed-when
  ansible.builtin.shell: |
    set ibmdb2_sid="{{ sap_ha_install_anydb_ibmdb2_sid }}"
    db2pd -hadr -db $ibmdb2_sid
  register: __sap_ha_install_anydb_ibmdb2_hadr_status
  become: true
  become_user: db2{{ sap_ha_install_anydb_ibmdb2_sid | lower }}
  args:
    executable: /bin/csh
  when:
    - sap_ha_install_anydb_ibmdb2_hostname_primary == inventory_hostname_short

- name: SAP HA AnyDB - IBM Db2 HADR - Display crm for IBM Db2 HA Linux Pacemaker initialisation
  ansible.builtin.debug:
    msg: "{{ __sap_ha_install_anydb_ibmdb2_pcmk_check.stdout_lines }}"
  when:
    - sap_ha_install_anydb_ibmdb2_hostname_primary == inventory_hostname_short

- name: SAP HA AnyDB - IBM Db2 HADR - Display db2cm for IBM Db2 HA Linux Pacemaker initialisation
  ansible.builtin.debug:
    msg: "{{ __sap_ha_install_anydb_ibmdb2_init_check.stdout_lines }}"
  when:
    - sap_ha_install_anydb_ibmdb2_hostname_primary == inventory_hostname_short

- name: SAP HA AnyDB - IBM Db2 HADR - Display IBM Db2 HADR configuration
  ansible.builtin.debug:
    msg: "{{ __sap_ha_install_anydb_ibmdb2_hadr_config.stdout_lines }}"
  when:
    - sap_ha_install_anydb_ibmdb2_hostname_primary == inventory_hostname_short

- name: SAP HA AnyDB - IBM Db2 HADR - Display IBM Db2 HADR status
  ansible.builtin.debug:
    msg: "{{ __sap_ha_install_anydb_ibmdb2_hadr_status.stdout_lines }}"
  when:
    - sap_ha_install_anydb_ibmdb2_hostname_primary == inventory_hostname_short

# Made with Bob
